<img align="left" src="https://lever-client-logos.s3.amazonaws.com/864372b1-534c-480e-acd5-9711f850815c-1524247202159.png" width=200>
<br></br>
<br></br>

# Sprint Challenge
## *Data Science Unit 4 Sprint 1*

After a week of Natural Language Processing, you've learned some cool new stuff: how to process text, how turn text into vectors, and how to model topics from documents. Apply your newly acquired skills to one of the most famous NLP datasets out there: [Yelp](https://www.yelp.com/dataset/challenge). As part of the job selection process, some of my friends have been asked to create analysis of this dataset, so I want to empower you to have a head start.  

The real dataset is massive (almost 8 gigs uncompressed). I've sampled the data for you to something more managable for the Sprint Challenge. You can analyze the full dataset as a stretch goal or after the sprint challenge. As you work on the challenge, I suggest adding notes about your findings and things you want to analyze in the future.

## Challenge Objectives
*Successfully complete these all these objectives to earn a 2. There are more details on each objective further down in the notebook.*
* <a href="#p1">Part 1</a>: Write a function to tokenize the yelp reviews
* <a href="#p2">Part 2</a>: Create a vector representation of those tokens
* <a href="#p3">Part 3</a>: Use your tokens in a classification model on yelp rating
* <a href="#p4">Part 4</a>: Estimate & Interpret a topic model of the Yelp reviews

In [1]:
import pandas as pd
import spacy
yelp = pd.read_json('./data/review_sample.json', lines=True)

In [2]:
yelp.head()

business_id  cool                date  funny  \
0  nDuEqIyRc8YKS1q1fX0CZg     1 2015-03-31 16:50:30      0   
1  eMYeEapscbKNqUDCx705hg     0 2015-12-16 05:31:03      0   
2  6Q7-wkCPc1KF75jZLOTcMw     1 2010-06-20 19:14:48      1   
3  k3zrItO4l9hwfLRwHBDc9w     3 2010-07-13 00:33:45      4   
4  6hpfRwGlOzbNv7k5eP9rsQ     1 2018-06-30 02:30:01      0   

                review_id  stars  \
0  eZs2tpEJtXPwawvHnHZIgQ      1   
1  DoQDWJsNbU0KL1O29l_Xug      4   
2  DDOdGU7zh56yQHmUnL1idQ      3   
3  LfTMUWnfGFMOfOIyJcwLVA      1   
4  zJSUdI7bJ8PNJAg4lnl_Gg      4   

                                                text  useful  \
0  BEWARE!!! FAKE, FAKE, FAKE....We also own a sm...      10   
1  Came here for lunch Togo. Service was quick. S...       0   
2  I've been to Vegas dozens of times and had nev...       2   
3  We went here on a night where they closed off ...       5   
4  3.5 to 4 stars\n\nNot bad for the price, $12.9...       5   

                  user_id  
0  n1LM36qNg4rqGXIcvVXv8w  
1  5CgjjDAic2-FAvCtiHpytA  
2  BdV-cf3LScmb8kZ7iiBcMA  
3  cZZnBqh4gAEy4CdNvJailQ  
4  n9QO4ClYAS7h9fpQwa5bhA

In [3]:
yelp.shape

(10000, 9)

## Part 1: Tokenize Function
<a id="#p1"></a>

Complete the function `tokenize`. Your function should
- accept one document at a time
- return a list of tokens

You are free to use any method you have learned this week.

In [4]:
def tokenize(doc):
    tokens = []
    for i in doc:
        token = i.split()
        tokens.append(token)
    return tokens

In [5]:
tokens = tokenize(yelp['text'])

In [6]:
tokens[0]

['BEWARE!!!',
 'FAKE,',
 'FAKE,',
 'FAKE....We',
 'also',
 'own',
 'a',
 'small',
 'business',
 'in',
 'Los',
 'Alamitos,',
 'CA',
 'and',
 'received',
 'what',
 'looked',
 'like',
 'a',
 'legitimate',
 'bill',
 'for',
 '$70',
 'with',
 'an',
 'account',
 'number',
 'and',
 'all.',
 'I',
 'called',
 'the',
 'phone',
 'number',
 'listed',
 '(866)',
 '273-7934.',
 'The',
 'wait',
 'time',
 'on',
 'hold',
 'said',
 '20',
 'minutes',
 'and',
 'to',
 'leave',
 'a',
 'message.',
 'I',
 'could',
 'not',
 'get',
 'a',
 'live',
 'person',
 'on',
 'the',
 'phone',
 'no',
 'matter',
 'what',
 'number',
 'I',
 'selected.',
 'I',
 'left',
 'a',
 'very',
 'FIRM',
 'message',
 'that',
 'I',
 'would',
 'be',
 'contacting',
 'the',
 'BBB',
 'and',
 'my',
 'attorney',
 'regarding',
 'their',
 'company',
 'trying',
 'to',
 'scam',
 'businesses.',
 'This',
 'has',
 'to',
 'be',
 'illegal!!!!!']

## Part 2: Vector Representation
<a id="#p2"></a>
1. Create a vector representation of the reviews
2. Write a fake review and query for the 10 most similiar reviews, print the text of the reviews. Do you notice any patterns?
    - Given the size of the dataset, it will probably be best to use a `NearestNeighbors` model for this. 

In [7]:
from sklearn.feature_extraction.text import TfidfVectorizer, CountVectorizer

vect = TfidfVectorizer(stop_words='english')
vect.fit(yelp['text'])
dtm = vect.transform(yelp['text'])

In [8]:
dtm = pd.DataFrame(dtm.todense(), columns=vect.get_feature_names())
dtm.head()

00  000  001695  007  00a  00am  00ish  00pm   01  011802  ...  誰も乗車しなくても  \
0  0.0  0.0     0.0  0.0  0.0   0.0    0.0   0.0  0.0     0.0  ...        0.0   
1  0.0  0.0     0.0  0.0  0.0   0.0    0.0   0.0  0.0     0.0  ...        0.0   
2  0.0  0.0     0.0  0.0  0.0   0.0    0.0   0.0  0.0     0.0  ...        0.0   
3  0.0  0.0     0.0  0.0  0.0   0.0    0.0   0.0  0.0     0.0  ...        0.0   
4  0.0  0.0     0.0  0.0  0.0   0.0    0.0   0.0  0.0     0.0  ...        0.0   

   豆腐花  質問にも丁寧に答えてくれましたし  車好きさんには  這是一個不錯的選擇  運転しない  運転中も英語で指導があります  食べ物はうまい  \
0  0.0               0.0      0.0        0.0    0.0             0.0      0.0   
1  0.0               0.0      0.0        0.0    0.0             0.0      0.0   
2  0.0               0.0      0.0        0.0    0.0             0.0      0.0   
3  0.0               0.0      0.0        0.0    0.0             0.0      0.0   
4  0.0               0.0      0.0        0.0    0.0             0.0      0.0   

   餐後點了甜點  ３時間後の便  
0     0.0     0.0  
1     0.0     0.0  
2     0.0     0.0  
3     0.0     0.0  
4     0.0     0.0  

[5 rows x 27289 columns]

In [29]:
from sklearn.neighbors import NearestNeighbors
from sklearn.model_selection import train_test_split
X = yelp['text']
y = yelp['stars']

X_train, X_test, y_train, y_test = train_test_split(X.values, y.values, test_size=0.2, random_state=42)

In [41]:
nn = NearestNeighbors(n_neighbors=10)

In [31]:
tvect = TfidfVectorizer(stop_words='english')
tvect.fit(X_train)

TfidfVectorizer(analyzer='word', binary=False, decode_error='strict',
                dtype=<class 'numpy.float64'>, encoding='utf-8',
                input='content', lowercase=True, max_df=1.0, max_features=None,
                min_df=1, ngram_range=(1, 1), norm='l2', preprocessor=None,
                smooth_idf=True, stop_words='english', strip_accents=None,
                sublinear_tf=False, token_pattern='(?u)\\b\\w\\w+\\b',
                tokenizer=None, use_idf=True, vocabulary=None)

In [32]:
X_train_vect = tvect.transform(X_train)
X_test_vect = tvect.transform(X_test)

In [42]:
nn.fit(X_train_vect)

NearestNeighbors(algorithm='auto', leaf_size=30, metric='minkowski',
                 metric_params=None, n_jobs=None, n_neighbors=10, p=2,
                 radius=1.0)

In [43]:
nn.kneighbors(X_test_vect)

(array([[1.20826708, 1.27093495, 1.27891828, ..., 1.30085817, 1.30392845,
         1.3078145 ],
        [1.32107594, 1.32467287, 1.32583723, ..., 1.33483665, 1.33490106,
         1.33512999],
        [1.23073474, 1.31289663, 1.317499  , ..., 1.33669281, 1.3371288 ,
         1.33745975],
        ...,
        [1.10398511, 1.10513004, 1.13361471, ..., 1.19074658, 1.19460748,
         1.19743097],
        [1.21945962, 1.31460339, 1.31670858, ..., 1.32735864, 1.3279665 ,
         1.3319115 ],
        [1.20748366, 1.25986734, 1.27098187, ..., 1.28823153, 1.29000406,
         1.29315066]]), array([[3917,  529, 6245, ..., 6427, 3760, 6515],
        [3284, 1099, 6350, ..., 7979,    6, 5148],
        [4653,   77, 1292, ..., 4023, 3975,  928],
        ...,
        [7126, 4816, 5016, ..., 2001, 5199,  377],
        [3549, 6881, 2398, ..., 1208, 1477, 2633],
        [4610, 6227, 3987, ..., 4435, 1868, 5072]], dtype=int64))

In [23]:
from sklearn.feature_extraction.text import CountVectorizer

cvect = CountVectorizer(stop_words='english')

In [44]:
review = 'Man this product sucked, 0 stars'
maybe = tvect.transform([review])
nn.kneighbors(maybe)

(array([[1.19947387, 1.2198087 , 1.24297435, 1.26709632, 1.26975577,
         1.27726142, 1.28060205, 1.28515086, 1.29622755, 1.29736893]]),
 array([[3329, 7083, 6419, 6820,  305, 1089, 3454, 5584,  585, 7027]],
       dtype=int64))

In [37]:
yelp['text'][7083]

'Both of my kids are students at Liberty prep. They enjoy going to school, have fun with class mates and their development has amazed me. Some of the teachers are new from last year due to two locations, but I am pleased with the teachers both in toddler and casa rooms....All are very approachable and informative.'

## Part 3: Classification
<a id="#p3"></a>
Your goal in this section will be to predict `stars` from the review dataset. 

1. Create a piepline object with a sklearn `CountVectorizer` or `TfidfVector` and any sklearn classifier. Use that pipeline to estimate a model to predict `stars`. Use the Pipeline to predict a star rating for your fake review from Part 2. 
2. Tune the entire pipeline with a GridSearch

In [46]:
from sklearn.pipeline import Pipeline
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import GridSearchCV

model = RandomForestClassifier()
pipe = Pipeline([('vect',tvect),('clf',model)])

params_grid = {
    "vect__min_df": (0.02, 0.05),
    "vect__max_df": (0.75, 1.0),
    "vect__max_features": (500, 1000),
    "clf__n_estimators": (5, 10),
    "clf__max_depth": (15, 20)
}

In [49]:
pipe.fit(X_train, y_train)

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\ensemble\forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)


Pipeline(memory=None,
         steps=[('vect',
                 TfidfVectorizer(analyzer='word', binary=False,
                                 decode_error='strict',
                                 dtype=<class 'numpy.float64'>,
                                 encoding='utf-8', input='content',
                                 lowercase=True, max_df=1.0, max_features=None,
                                 min_df=1, ngram_range=(1, 1), norm='l2',
                                 preprocessor=None, smooth_idf=True,
                                 stop_words='english', strip_accents=None,
                                 sublinear_tf=False,
                                 token_patte...
                 RandomForestClassifier(bootstrap=True, class_weight=None,
                                        criterion='gini', max_depth=None,
                                        max_features='auto',
                                        max_leaf_nodes=None,
                               

In [51]:
pipe.predict([review])

array([5], dtype=int64)

In [47]:
grid_search = GridSearchCV(estimator=pipe, param_grid=params_grid, cv=5, n_jobs=-1, verbose=1)

In [ ]:
grid_search.fit

## Part 4: Topic Modeling

Let's find out what those yelp reviews are saying! :D

1. Estimate a LDA topic model of the review text
2. Create 1-2 visualizations of the results
    - You can use the most important 3 words of a topic in relevant visualizations. Refer to yesterday's notebook to extract. 
3. In markdown, write 1-2 paragraphs of analysis on the results of your topic model

__*Note*__: You can pass the DataFrame column of text reviews to gensim. You do not have to use a generator.

## Stretch Goals

Complete one of more of these to push your score towards a three: 
* Incorporate named entity recognition into your analysis
* Compare vectorization methods in the classification section
* Analyze more (or all) of the yelp dataset - this one is v. hard. 
* Use a generator object on the reviews file - this would help you with the analyzing the whole dataset.
* Incorporate any of the other yelp dataset entities in your analysis (business, users, etc.)